# --- Green hacker style ---

# Colors
foreground              #00FF00
background              #000000
background_opacity  0.8

# Cursor
cursor_shape            block
cursor_blink            yes
cursor_text_color       #000000

# Font
font_family             monospace
font_size               14.0

# window
window_padding_width    10
